### ISSUE TITLE
AUR cmd-polkit-git error

### ISSUE THREAD

**Issue by joeydc** [czaplicki/rofi-polkit-agent#1]
I'm getting an error upgrading the package CMD-POLKIT-GIT from the AUR.

> ==> Starting pkgver()...
/home/joeydc/.cache/yay/cmd-polkit-git/PKGBUILD: line 15: cd: cmd-polkit-git-r8.069d66b: No such file or directory
==> ERROR: A failure occurred in pkgver().
    Aborting...
 -> error making: cmd-polkit-git

![image](https://user-images.githubusercontent.com/8237849/206927266-ac4ecc91-07a0-4eff-8c4e-38750aecdb24.png)

**Comment by czaplicki** [comment]
Thanks for letting me know, the issue should now be resolved!

The issue was that `cmd-polkit-git` package was out of date.
Since I'm the maintainer of sed package it worked reaching out through this repository.
But next time try to leave a comment on the AUR, since this issue isn't really related to this repository.
